//! Pinned destination directory and transactional sibling publication.
use crate::{Error, Result, WorkspaceRoot, content::checked_relative};
use cap_std::fs::{Dir, OpenOptions};
use std::{
    ffi::OsString,
    fs::File,
    path::{Component, Path, PathBuf},
    sync::atomic::{AtomicBool, Ordering},
};

pub const TEMP_PREFIX: &str = ".contextpick-export-";

pub struct Destination {
    root: WorkspaceRoot,
    parent: Dir,
    parent_path: PathBuf,
    relative_parent: Option<PathBuf>,
    relative_path: Option<String>,
    name: OsString,
    path: PathBuf,
    overwrite: bool,
}

fn comparable(path: &Path) -> PathBuf {
    #[cfg(windows)]
    if let Some(path) = path.to_str() {
        if let Some(tail) = path.strip_prefix(r"\\?\UNC\") {
            return PathBuf::from(format!(r"\\{tail}"));
        }
        if let Some(tail) = path.strip_prefix(r"\\?\") {
            return PathBuf::from(tail);
        }
    }
    path.to_path_buf()
}

fn open_components(mut parent: Dir, relative: &Path) -> Result<Dir> {
    for component in relative.components() {
        let Component::Normal(name) = component else {
            return Err(Error::Message("unsafe destination parent".into()));
        };
        let start = parent.into_std_file();
        parent = Dir::from_std_file(cap_primitives::fs::open_dir_nofollow(
            &start,
            Path::new(name),
        )?);
    }
    Ok(parent)
}

fn open_absolute_nofollow(path: &Path) -> Result<Dir> {
    let mut anchor = PathBuf::new();
    let mut relative = PathBuf::new();
    for component in path.components() {
        match component {
            Component::Prefix(_) | Component::RootDir => anchor.push(component.as_os_str()),
            Component::Normal(_) => relative.push(component.as_os_str()),
            _ => return Err(Error::Message("unsafe destination parent".into())),
        }
    }
    let parent = Dir::open_ambient_dir(anchor, cap_std::ambient_authority())?;
    open_components(parent, &relative)
}

fn reject_in_root_links(root: &WorkspaceRoot, original: &Path) -> Result<bool> {
    let root_path = comparable(root.path());
    let mut prefix = PathBuf::new();
    let mut inside = false;
    for component in original.components() {
        prefix.push(component.as_os_str());
        if matches!(component, Component::Prefix(_)) {
            continue;
        }
        if matches!(component, Component::CurDir | Component::ParentDir) {
            return Err(Error::Message("unsafe destination parent".into()));
        }
        if inside {
            let metadata = std::fs::symlink_metadata(&prefix)?;
            let mut linked = metadata.file_type().is_symlink();
            #[cfg(windows)]
            {
                use std::os::windows::fs::MetadataExt;
                linked |= metadata.file_attributes() & 0x400 != 0;
            }
            if linked {
                return Err(Error::Message(
                    "link or reparse point in workspace destination parent".into(),
                ));
            }
        }
        // Resolve actual spelling instead of assuming the filesystem's case
        // mode. System aliases before the root (e.g. macOS /var) are allowed.
        inside |= comparable(&std::fs::canonicalize(&prefix)?).starts_with(&root_path);
    }
    Ok(inside)
}

fn pin_parent(
    root: &WorkspaceRoot,
    original: &Path,
    canonical: &Path,
) -> Result<(Dir, Option<PathBuf>)> {
    let entered_root = reject_in_root_links(root, original)?;
    let relative = comparable(canonical)
        .strip_prefix(comparable(root.path()))
        .ok()
        .map(Path::to_path_buf);
    if entered_root && relative.is_none() {
        return Err(Error::Message(
            "destination ancestry changed during validation; choose it again".into(),
        ));
    }
    let parent = match &relative {
        Some(relative) => open_components(root.dir().try_clone()?, relative)?,
        None => open_absolute_nofollow(canonical)?,
    };
    let chosen = same_file::Handle::from_path(original)?;
    let pinned = same_file::Handle::from_file(parent.try_clone()?.into_std_file())?;
    if chosen != pinned {
        return Err(Error::Message(
            "destination parent changed during validation; choose it again".into(),
        ));
    }
    Ok((parent, relative))
}

impl Destination {
    /// Prepare without writing. In-root callers persist `relative_path()` as a
    /// hard exclusion before calling create_temp. Existing in-root files are
    /// never replaced, even if they were previously generated by ContextPick.
    pub fn prepare(root: &WorkspaceRoot, path: &Path, overwrite: bool) -> Result<Self> {
        root.validate_anchor()?;
        let absolute = if path.is_absolute() {
            path.to_path_buf()
        } else {
            std::env::current_dir()?.join(path)
        };
        let name = absolute
            .file_name()
            .ok_or_else(|| Error::Message("destination has no filename".into()))?
            .to_owned();
        let name_text = name
            .to_str()
            .ok_or_else(|| Error::Message("destination filename is not valid Unicode".into()))?;
        checked_relative(name_text)?;
        if name_text.starts_with(TEMP_PREFIX) {
            return Err(Error::Message(
                "destination uses the reserved export temporary prefix".into(),
            ));
        }
        let original_parent = absolute
            .parent()
            .ok_or_else(|| Error::Message("destination has no parent".into()))?;
        let canonical_parent = std::fs::canonicalize(original_parent)?;
        let (parent, relative_parent) = pin_parent(root, original_parent, &canonical_parent)?;
        let relative_path = relative_parent
            .as_ref()
            .map(|parent| parent.join(&name).to_string_lossy().replace('\\', "/"));
        if let Some(relative) = &relative_path {
            checked_relative(relative)?;
        }
        let metadata = match parent.symlink_metadata(&name) {
            Ok(metadata) => Some(metadata),
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => None,
            Err(error) => return Err(error.into()),
        };
        if let Some(metadata) = metadata {
            let mut link = metadata.file_type().is_symlink();
            #[cfg(windows)]
            {
                use cap_std::fs::MetadataExt;
                link |= metadata.file_attributes() & 0x400 != 0;
            }
            if link || !metadata.is_file() {
                return Err(Error::Message(
                    "destination must be a regular file, not a link".into(),
                ));
            }
            if relative_path.is_some() {
                return Err(Error::Message(
                    "an existing workspace file cannot be replaced; choose a new export filename"
                        .into(),
                ));
            }
            if !overwrite {
                return Err(Error::Message(
                    "destination already exists; overwrite confirmation required".into(),
                ));
            }
        }
        let destination = Self {
            root: root.clone(),
            parent,
            parent_path: canonical_parent.clone(),
            relative_parent,
            relative_path,
            name,
            path: path.to_path_buf(),
            overwrite,
        };
        destination.validate_parent()?;
        Ok(destination)
    }

    pub fn relative_path(&self) -> Option<&str> {
        self.relative_path.as_deref()
    }
    pub fn path(&self) -> &Path {
        &self.path
    }

    fn validate_parent(&self) -> Result<()> {
        self.root.validate_anchor()?;
        let current = match &self.relative_parent {
            Some(relative) => open_components(self.root.dir().try_clone()?, relative)?,
            None => open_absolute_nofollow(&self.parent_path)?,
        };
        let expected = same_file::Handle::from_file(self.parent.try_clone()?.into_std_file())?;
        let actual = same_file::Handle::from_file(current.into_std_file())?;
        if expected != actual {
            return Err(Error::Message(
                "destination parent changed; choose the destination again".into(),
            ));
        }
        Ok(())
    }

    pub fn create_temp(self) -> Result<OutputTransaction> {
        self.validate_parent()?;
        for _ in 0..16 {
            let mut random = [0u8; 16];
            getrandom::fill(&mut random).map_err(|error| {
                Error::Message(format!(
                    "temporary filename randomness unavailable: {error}"
                ))
            })?;
            let suffix: String = random.iter().map(|byte| format!("{byte:02x}")).collect();
            let name = format!("{TEMP_PREFIX}{suffix}.tmp");
            let mut options = OpenOptions::new();
            options.write(true).create_new(true);
            match self.parent.open_with(&name, &options) {
                Ok(file) => {
                    return Ok(OutputTransaction {
                        destination: self,
                        name,
                        file: Some(file.into_std()),
                    });
                }
                Err(error) if error.kind() == std::io::ErrorKind::AlreadyExists => continue,
                Err(error) => return Err(error.into()),
            }
        }
        Err(Error::Message(
            "could not reserve an export temporary sibling".into(),
        ))
    }
}

pub struct OutputTransaction {
    destination: Destination,
    name: String,
    file: Option<File>,
}
impl OutputTransaction {
    pub fn file_mut(&mut self) -> &mut File {
        self.file.as_mut().expect("transaction file is open")
    }
    pub fn commit(mut self, cancel: &AtomicBool) -> Result<()> {
        self.file_mut().sync_all()?;
        self.file.take();
        self.destination.validate_parent()?;
        if cancel.load(Ordering::Relaxed) {
            return Err(Error::Message("export cancelled".into()));
        }
        if self.destination.relative_path.is_none() && self.destination.overwrite {
            self.destination.parent.rename(
                &self.name,
                &self.destination.parent,
                &self.destination.name,
            )?;
        } else {
            // Link publication is atomic and fails if ANY target appeared while
            // streaming. Rename would replace it and could destroy a source.
            self.destination.parent.hard_link(
                &self.name,
                &self.destination.parent,
                &self.destination.name,
            )?;
            // Publication succeeded. Drop performs best-effort cleanup; a
            // cleanup failure must not turn a complete export into an error.
        }
        Ok(())
    }
}
impl Drop for OutputTransaction {
    fn drop(&mut self) {
        self.file.take();
        let _ = self.destination.parent.remove_file(&self.name);
    }
}

#[cfg(all(test, windows))]
mod tests {
    use super::*;

    #[test]
    fn junction_replaced_after_canonicalization_cannot_authorize_outside_overwrite() {
        let root_dir = tempfile::tempdir().unwrap();
        let outside = tempfile::tempdir().unwrap();
        let root = WorkspaceRoot::open(root_dir.path()).unwrap();
        let original_parent = root_dir.path().join("changed");
        std::fs::write(outside.path().join("context.md"), "outside original").unwrap();
        let command = std::process::Command::new("cmd")
            .args(["/C", "mklink", "/J"])
            .arg(&original_parent)
            .arg(outside.path())
            .output()
            .unwrap();
        assert!(
            command.status.success(),
            "junction fixture prerequisite failed"
        );
        let canonical_before = std::fs::canonicalize(&original_parent).unwrap();
        std::fs::remove_dir(&original_parent).unwrap();
        std::fs::create_dir(&original_parent).unwrap();
        std::fs::write(original_parent.join("context.md"), "inside source").unwrap();
        assert!(pin_parent(&root, &original_parent, &canonical_before).is_err());
        assert_eq!(
            std::fs::read_to_string(outside.path().join("context.md")).unwrap(),
            "outside original"
        );
        assert_eq!(
            std::fs::read_to_string(original_parent.join("context.md")).unwrap(),
            "inside source"
        );
    }
}
